#!/bin/bash

REPOSITORY_NAME="tnnsst35/websocket-sample"

GUEST_HOST_NAME="webview-sample"

HOST_FORWARDING_PORT="8080"
GUEST_FORWARDING_PORT="8080"

HOST_MOUNT_PATH=`pwd`
GUEST_MOUNT_PATH="/workspace"